name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t my-nginx-container .

      - name: Run Docker Container
        run: docker run -d -p 80:80 my-nginx-container

      - name: Test Container Accessibility
        run: curl localhost:80
